#
all: coap-post

WITH_SE95_SENSOR=0
WITH_TMP102_SENSOR=1
WITH_BUTTON_SENSOR=1
WITH_OW_TEMP_SENSORS=1
WITH_MMS_BOARD=1
WITH_UDPCLIENT?=1

# UDP client configuration
UDP_PERIOD?=60
WITH_UDP_CLIENT_AUTOSTART?=1

CONTIKI= contiki
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

SMALL=1

# REST Engine shall use Erbium CoAP implementation
APPS += er-coap
APPS += rest-engine

PROJECTDIR?=.
PROJECTDIRS += dev

APPDIRS += $(PROJECTDIR)/apps
PROJECTDIRS += $(PROJECTDIR)/apps/udp-client

ifeq ($(WITH_MMS_BOARD),1)
CFLAGS += -DWITH_MMS_BOARD=1
endif
ifeq ($(WITH_SE95_SENSOR),1)
CFLAGS += -DWITH_SE95_SENSOR=1
PROJECT_SOURCEFILES += se95-sensor.c
endif
ifeq ($(WITH_TMP102_SENSOR),1)
CFLAGS += -DWITH_TMP102_SENSOR=1
PROJECT_SOURCEFILES += tmp102-sensor.c
endif
ifeq ($(WITH_BUTTON_SENSOR),1)
CFLAGS += -DWITH_BUTTON_SENSOR=1
endif
ifeq ($(WITH_OW_TEMP_SENSORS),1)
CFLAGS += -DWITH_OW_TEMP_SENSORS=1
PROJECT_SOURCEFILES += ds2482.c
PROJECT_SOURCEFILES += ds1820.c
endif
ifneq ($(WITH_UDPCLIENT),0)
CFLAGS += -DWITH_UDPCLIENT=1
PROJECT_SOURCEFILES += udp-client.c
else
CFLAGS += -DWITH_UDPCLIENT=0
endif

ifneq ($(UDP_PERIOD),)
CFLAGS += -DCETIC_6LBR_UDP_PERIOD=$(UDP_PERIOD)
endif

ifneq ($(WITH_UDP_CLIENT_AUTOSTART),0)
CFLAGS += -DUDP_CLIENT_AUTOSTART=1
endif

PROJECT_SOURCEFILES += nvm-config.c

VERSION_STRING := $(shell git rev-parse --verify --short HEAD)
CFLAGS += -DVERSION_STRING=\"cc2538_coap_sensor-${VERSION_STRING}\"

include $(CONTIKI)/Makefile.include
